import type { NextPage } from 'next';
import Head from 'next/head';
import Image from 'next/image';
import { Navigation, Hero } from '../components';

const Home: NextPage = () => {
  return (
    <section>
      {/* <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head> */}
      <Navigation />
      <Hero />
    </section>
  );
};

export default Home;
