import type { NextPage } from 'next';
import Head from 'next/head';
import {
  Navigation,
  Hero,
  Trending,
  TopRated,
  Action,
  Comedy,
  Horror,
  Documentaries,
  Romance,
} from '../components';

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navigation />
      <Hero />
      <Trending />
      <TopRated />
      <Action />
      <Comedy />
      <Horror />

      <Documentaries />
      <Romance />
    </>
  );
};

export default Home;
