import { Navigation, Lists } from '../components';
import Head from 'next/head';

const activePage = 'My List';

const List = () => {
  return (
    <section>
      <Head>
        <title>{activePage} - Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>

      <Navigation activePage={activePage} />
      <Lists />
    </section>
  );
};

export default List;
