import { Navigation } from '../components';
import Head from 'next/head';

const List = () => {
  // const { heroMovie } = useSelector((store: RootState) => store.shows);
  return (
    <section>
      <Head>
        <title>My List - Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>
      <Navigation />
      <div>List</div>;
    </section>
  );
};

export default List;
