import Head from 'next/head';
import { Hero, Trending, Documentaries, Romance } from '../components';
import { useSelector } from 'react-redux';
import { RootState } from '../redux/store';
import { getMoviesHero } from '../redux/features/moviesSlice';
import {
  getTrendingMovies,
  getDocumentaries,
  getRomance,
} from '../redux/features/homeSlice';
import { useEffect } from 'react';
import { useDispatch } from 'react-redux';
const Movies = () => {
  const { moviesHero } = useSelector((store: RootState) => store.movies);
  const activePage = 'Movies';

  const dispatch = useDispatch();
  useEffect(() => {
    dispatch(getMoviesHero());
    dispatch(getTrendingMovies());
    dispatch(getDocumentaries());
    dispatch(getRomance());
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, []);
  return (
    <section>
      <Head>
        <title>{activePage} - Netflix</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.png' />
      </Head>
      <div className='overflow-hidden '>
        <Hero heroMovieProp={moviesHero} activePage={activePage} />
        <Trending />
        <Documentaries />
        <Romance />
      </div>
    </section>
  );
};

export default Movies;
